apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service-account.yaml
  - vault-auth.yaml
  - vault-dynamic-secret.yaml
  - vault-public-jwt.yaml
  - vault-redis-secret.yaml
  - vault-sentinel-secret.yaml
  - deployment.yaml
  - service.yaml
  - extra.yaml

labels:
  - pairs:
      app.kubernetes.io/name: scheduling-service
      app.kubernetes.io/part-of: whispr
    includeSelectors: false
