---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scheduling-service-sa
  labels:
    app: scheduling-service
  annotations:
    argocd.argoproj.io/sync-wave: "0"
automountServiceAccountToken: true
