---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: scheduling-service-vault-auth
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  vaultConnectionRef: default
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: scheduling-service
    serviceAccount: scheduling-service-sa
    audiences:
      - vault
