apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: whispr-staging
resources:
- ../../../base/messaging-service
- configmap.yaml
labels:
- pairs:
    environment: staging
  includeSelectors: false
images:
- name: ghcr.io/whispr-messenger/messaging-service/messaging-service
  newTag: sha-fbeb709
