apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: whispr-staging
resources:
- ../../../base/messaging-service
- configmap.yaml
labels:
- pairs:
    environment: staging
  includeSelectors: false
patches:
- target:
    group: secrets.hashicorp.com
    version: v1beta1
    kind: VaultAuth
    name: messaging-service-vault-auth
  patch: |
    - op: replace
      path: /spec/kubernetes/role
      value: messaging-service-staging
- target:
    group: secrets.hashicorp.com
    version: v1beta1
    kind: VaultDynamicSecret
    name: messaging-service-db-creds
  patch: |
    - op: replace
      path: /spec/path
      value: creds/role_messaging_service_staging
- target:
    group: secrets.hashicorp.com
    version: v1beta1
    kind: VaultDynamicSecret
    name: messaging-service-redis-creds
  patch: |
    - op: replace
      path: /spec/path
      value: creds/redis_role_messaging_service_staging

images:
- name: ghcr.io/whispr-messenger/messaging-service/messaging-service
  newTag: sha-9e08fa4
