---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-service-sa
  labels:
    app: notification-service
  annotations:
    argocd.argoproj.io/sync-wave: "0"
automountServiceAccountToken: true
