---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: notification-service-redis-creds
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  vaultAuthRef: notification-service-vault-auth
  mount: database
  path: creds/redis_role_notification_service
  destination:
    create: true
    name: notification-service-redis-secret
  rolloutRestartTargets:
    - kind: Deployment
      name: notification-service
  renewalPercent: 67
  revoke: true
