---
apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: whispr
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  promotionPolicies:
    - stage: staging
      autoPromotionEnabled: true
    - stage: production
      autoPromotionEnabled: false
