---
apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: whispr
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  promotionPolicies:
    - stage: auth-service-staging
      autoPromotionEnabled: true
    - stage: auth-service-production
      autoPromotionEnabled: false
    - stage: media-service-staging
      autoPromotionEnabled: true
    - stage: media-service-production
      autoPromotionEnabled: false
    - stage: messaging-service-staging
      autoPromotionEnabled: true
    - stage: messaging-service-production
      autoPromotionEnabled: false
    - stage: notification-service-staging
      autoPromotionEnabled: true
    - stage: notification-service-production
      autoPromotionEnabled: false
    - stage: scheduling-service-staging
      autoPromotionEnabled: true
    - stage: scheduling-service-production
      autoPromotionEnabled: false
    - stage: user-service-staging
      autoPromotionEnabled: true
    - stage: user-service-production
      autoPromotionEnabled: false
