---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: whispr-images
  namespace: whispr
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  subscriptions:
    - image:
        repoURL: ghcr.io/whispr-messenger/auth-service/auth-service
        semverConstraint: ""
        discoveryPolicy: SemVer
        allowTags: "^sha-.+$"
    - image:
        repoURL: ghcr.io/whispr-messenger/media-service/media-service
        semverConstraint: ""
        discoveryPolicy: SemVer
        allowTags: "^sha-.+$"
    - image:
        repoURL: ghcr.io/whispr-messenger/messaging-service/messaging-service
        semverConstraint: ""
        discoveryPolicy: SemVer
        allowTags: "^sha-.+$"
    - image:
        repoURL: ghcr.io/whispr-messenger/notification-service
        semverConstraint: ""
        discoveryPolicy: SemVer
        allowTags: "^sha-.+$"
    - image:
        repoURL: ghcr.io/whispr-messenger/scheduling-service/scheduling-service
        semverConstraint: ""
        discoveryPolicy: SemVer
        allowTags: "^sha-.+$"
    - image:
        repoURL: ghcr.io/whispr-messenger/user-service/user-service
        semverConstraint: ""
        discoveryPolicy: SemVer
        allowTags: "^sha-.+$"
