apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: whispr-staging
resources:
- ../../../base/media-service
- configmap.yaml
labels:
- pairs:
    environment: staging
  includeSelectors: false

patches:
- target:
    group: secrets.hashicorp.com
    version: v1beta1
    kind: VaultAuth
    name: media-service-vault-auth
  patch: |
    - op: replace
      path: /spec/kubernetes/role
      value: media-service-staging

images:
- name: ghcr.io/whispr-messenger/media-service/media-service
  newTag: sha-398b7b6
