apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: whispr-staging

resources:
  - ../../../base/media-service
  - configmap.yaml

labels:
  - pairs:
      environment: staging
    includeSelectors: false

images:
  - name: ghcr.io/whispr-messenger/media-service/media-service
    newTag: sha-9c36c35
