apiVersion: v1
kind: ServiceAccount
metadata:
  name: messaging-service-sa
  labels:
    app: messaging-service
  annotations:
    argocd.argoproj.io/sync-wave: "0"
automountServiceAccountToken: true
