---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: messaging-service-redis-sentinel
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  vaultAuthRef: messaging-service-vault-auth
  mount: kv
  type: kv-v2
  path: whispr/shared/redis
  destination:
    name: messaging-service-redis-sentinel-secret
    create: true
  refreshAfter: 1h
