---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: messaging-service-app-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  vaultAuthRef: messaging-service-vault-auth
  mount: kv
  type: kv-v2
  path: whispr/messaging-service/secrets
  destination:
    name: messaging-service-app-secret
    create: true
  rolloutRestartTargets:
    - kind: Deployment
      name: messaging-service
  refreshAfter: 1h
