apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: whispr-staging
resources:
- ../../../base/notification-service
- configmap.yaml
labels:
- pairs:
    environment: staging
  includeSelectors: false
patches:
- target:
    group: secrets.hashicorp.com
    version: v1beta1
    kind: VaultAuth
    name: notification-service-vault-auth
  patch: |
    - op: replace
      path: /spec/kubernetes/role
      value: notification-service-staging
- target:
    group: secrets.hashicorp.com
    version: v1beta1
    kind: VaultDynamicSecret
    name: notification-service-db-creds
  patch: |
    - op: replace
      path: /spec/path
      value: creds/role_notification_service_staging

images:
- name: ghcr.io/whispr-messenger/notification-service
  newTag: sha-c4b0322
