apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: whispr-staging

resources:
  - ../../../base/notification-service
  - configmap.yaml

labels:
  - pairs:
      environment: staging
    includeSelectors: false

images:
  - name: ghcr.io/whispr-messenger/notification-service
    newTag: sha-7bbe53d
