apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: whispr-staging
resources:
- ../../../base/user-service
- configmap.yaml
labels:
- pairs:
    environment: staging
  includeSelectors: false
images:
- name: ghcr.io/whispr-messenger/user-service/user-service
  newTag: sha-0180359
