apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: whispr-staging
resources:
- ../../../base/auth-service
- configmap.yaml
labels:
- pairs:
    environment: staging
  includeSelectors: false
patches:
- target:
    group: secrets.hashicorp.com
    version: v1beta1
    kind: VaultAuth
    name: auth-service-vault-auth
  patch: |
    - op: replace
      path: /spec/kubernetes/role
      value: auth-service-staging
- target:
    group: secrets.hashicorp.com
    version: v1beta1
    kind: VaultDynamicSecret
    name: auth-service-db-creds
  patch: |
    - op: replace
      path: /spec/path
      value: creds/role_auth_service_staging
- target:
    group: secrets.hashicorp.com
    version: v1beta1
    kind: VaultDynamicSecret
    name: auth-service-redis-creds
  patch: |
    - op: replace
      path: /spec/path
      value: creds/redis_role_auth_service_staging
images:
- name: ghcr.io/whispr-messenger/auth-service/auth-service
  newTag: sha-05eb3ef
