---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: media-service-minio-creds
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  vaultAuthRef: media-service-vault-auth
  mount: kv
  type: kv-v2
  path: whispr/media-service/minio
  destination:
    name: media-service-minio-secret
    create: true
  refreshAfter: 1h
